/* ==========================================================================
 * data.js — raw protocol data extracted verbatim from iafan/Hacksby
 * (https://github.com/iafan/Hacksby, Perl, MIT License, Copyright (C) 2013 Igor Afanasyev)
 *
 *   CHECKSUM_64  <- lib/Furby/Packet.pm        (64 checksums, no known formula)
 *   CMD_LIST     <- lib/Furby/Command.pm       (~152 named commands)
 *   DICTIONARY   <- lib/Furby/Command/Dictionary.pm (~352 Furbish phrases)
 *
 * This file holds DATA ONLY — no logic. See protocol.js for how it's used.
 * ========================================================================== */
(function (root) {
const D = root.FurbyData = root.FurbyData || {};
const CHECKSUMS_64 = ["0000","0110","0210","0300","1023","1133","1233","1323","0120","0201","0330","1021","1103","1222","1313","2021","0220","0330","1000","1110","1203","1313","2000","2110","0300","1011","1120","1201","1323","2011","2120","2201","1033","1123","1223","1333","2033","2123","2223","2333","1113","1232","1303","2031","2113","2232","2303","3012","1213","1303","2010","2100","2213","2303","3033","3123","1333","2001","2130","2211","2333","3022","3113","3232"];

const CMD_LIST = [
  [350,"","food, tasty (\"mmm, yum\")",1],
  [352,"Any small eatable tasty stuff (like peanut)","",1],
  [353,"Any bigger soft eatable tasty stuff (like banana)","",1],
  [354,"Any suckable tasty stuff (like oysters, sphagetti)","",1],
  [355,"Any drinkable(?) tasty stuff","",1],
  [356,"Any hard eatable but not tasty stuff (like chicken bone)","",1],
  [358,"Any small not tasty stuff (like pepperoni)","",1],
  [359,"Any bigger soft not tasty stuff (like asparagus)","",1],
  [360,"Any suckable not tasty stuff ","",1],
  [361,"","",1],
  [368,"","",1],
  [370,"","",1],
  [371,"","",1],
  [372,"Any suckable tasty stuff (like beans)","\"ooh!\"",1],
  [373,"","",1],
  [374,"","",1],
  [376,"","",1],
  [377,"","",1],
  [378,"","",1],
  [379,"","",1],
  [380,"","",1],
  [382,"","",1],
  [383,"","",1],
  [384,"","",1],
  [385,"","",1],
  [386,"","",1],
  [388,"","",1],
  [389,"","",1],
  [390,"","",1],
  [391,"","",1],
  [392,"","",1],
  [394,"","",1],
  [395,"","",1],
  [396,"","",1],
  [397,"","",1],
  [398,"","",1],
  [400,"","",1],
  [401,"","",1],
  [402,"","",1],
  [403,"","",1],
  [410,"","something hot?",1],
  [412,"","something hot?",1],
  [413,"","something hot?",1],
  [414,"","",1],
  [415,"","",1],
  [416,"","",1],
  [417,"Any non-eatable stuff (toilet paper, pillow, etc)","",1],
  [418,"","",1],
  [419,"","",1],
  [420,"","",1],
  [421,"","",1],
  [422,"","",1],
  [423,"","",1],
  [424,"","",1],
  [425,"","",1],
  [700,"Event: I'm bored / sleepy","does various silly things depending on personality",0],
  [701,"Event: Burp","",0],
  [702,"Event: Chew-chew","",0],
  [703,"Event: You touched my head or side, you turned me on a side","",0],
  [704,"Event: Fart","",0],
  [705,"Event: I woke up!","sent on Furby wakeup, even before it pronounces the 'Good morning' phrase",0],
  [706,"Event: (?)","sent at random when Furby is idle (like ping, or searching for other Furbys?). Responds with '721'",0],
  [707,"Event: (?)","sent at random when Furby is idle (like ping, or searching for other Furbys?). Responds with '722'",0],
  [708,"Event: (?)","speech: dang-dang-dang-da..... Responds with '723'",0],
  [709,"Event: (?)","speech: bo-ga-di-di-do ... dang-dang-dang-da..... Responds with '724'",0],
  [710,"Event: Me happy (also when head or back is touched)","",0],
  [711,"Event: cough-cough-cough","",0],
  [712,"Event: Me hungry! / Kah Ay-tay!","",0],
  [713,"Event: You touched my tummy; also sent on its own like <touch my tummy, please?> / As command: imitate tummy touch(?)","<",0],
  [714,"","something that he dislikes (vomit like sound, changes eyes)",0],
  [715,"","something he dislikes? speaks rapidly",0],
  [716,"Event: Me happy (you touched my side or back, or head)","",0],
  [717,"Event: Achoo!","",0],
  [718,"Event: Yawn (I'm going to sleep) / As command: Yawn!","when sent as a command, will yawn / sent automatically twice when Furby is going into deep sleep mode",0],
  [719,"Event: Whisper, whisper, he-he-he","",0],
  [720,"","something he dislikes, \"uh oh kaa tee, do?\"",0],
  [721,"Event: got a command 706 (plus sings a song); as command: sing that song","handshake?",1],
  [722,"Event: got a command 707 (plus sings a song); as command: sing that song","handshake?",1],
  [723,"Event: got a command 708 (plus sings a song); as command: sing that song","handshake?",1],
  [724,"Event: got a command 709 (plus sings a song); as command: sing that song","handshake?",1],
  [760,"","\"love friend, nay nay noo la\"",0],
  [761,"","\"day-dee\"",0],
  [762,"","\"meila koo mei ta, meila koo mei ta, like mua, mua, mua\" (kiss)",0],
  [763,"","\"ka tulu ata, ata, ata, ata\" (song)",0],
  [764,"","\"witi wati to to, blah blah blah blah blah, blah\" (song)",0],
  [765,"","\"(fart) oh-ho-ho, tu lu li ku!\"",0],
  [766,"","\"boda tei ta eÑ ku, shaa!\"",0],
  [780,"Event: I've got command 790","",0],
  [781,"Event: I've got command 791","",0],
  [790,"","\"ee day do lay lo la!\". Responds with '780'",0],
  [791,"","\"u nai bo li day\". Responds with '781'",0],
  [813,"Request: What's your personality?","used to initate handshake step 1 and get the current personality type",1],
  [820,"Hypnotize for 1 minute","this command is sent by iOS app immediately on application start and every 40 seconds. Responds with current character type (90x).",1],
  [830,"","",1],
  [831,"","",0],
  [832,"","",1],
  [850,"","\"yeah mi mi be day mu ha ha\", \"yeah, yeah, yeah! oh yeah yeah!\"",0],
  [851,"","\"mmm, ka tulu, me like\", \"haa\"",0],
  [852,"","\"oh-oh-oh-oh!\", \"dude, no!\"",0],
  [853,"","\"grrrh ko ko\" something he dislikes",0],
  [854,"","\"grrrh ko ko\", \"ka bu ku do\"",0],
  [855,"","\"ka happy dude\", \"a ha pee pee day\", \"yeah nice good boo tai naba\"",0],
  [856,"","\"u-ho-ho, a-ho-ho\", \"blah blah blah blah\"",0],
  [857,"","\"a ha! bu da to to\", \"u ha, he-he-he\"",0],
  [858,"","\"ha? du?\"",0],
  [859,"","\"a ha\", \"oh, kah hey hey, I see\"",0],
  [860,"","\"ahaa.. be day loo ney\", \"haa\", \"um, mmm, hm\"",0],
  [861,"","\"huh\" (bored?)",0],
  [862,"Command: Sleep!","sleep (for several seconds)",1],
  [863,"Command: Laugh!","laugh",1],
  [864,"Command: Burp!","burp",1],
  [865,"Command: Fart!","fart/poo",1],
  [866,"Command: Purr!","purr",1],
  [867,"Command: Sneeze!","long sneeze",1],
  [868,"Command: Sing!","sing",1],
  [869,"Command: Talk!","talk",1],
  [870,"","\"me tay, yes, yes!\" (hearts in his eyes), \"di do dude, good friend\"",0],
  [871,"","\"ah bu to lu, no like\"",0],
  [872,"","says some rap",0],
  [873,"","sings: \"di-di-di-di, tam-da-di dam\"",0],
  [874,"","eating motion",0],
  [875,"","angry bite, \"he-he-he\"",0],
  [876,"","chewing/sucking sound (like when someone puts a finger in his mouth)",0],
  [877,"","suck in",0],
  [878,"","ingest",0],
  [879,"","short sneeze, \"like pea\" (or something else, depending on personality)",0],
  [880,"","motion (dislike)",1],
  [881,"","\"oh-hoo ha-ha\" (or \"ha-haa\" like something scary or hot)",0],
  [882,"","\"ah ha me bee dey, nice good!\", purr",1],
  [883,"","tasty: \"mmm, yum\", \"ha haa!\"",0],
  [884,"","not tasty (vomit-like)",0],
  [885,"","\"oooh\"",0],
  [886,"","\"chew chew ooh\"",0],
  [887,"","\"aaah\" (exclamation) (changes eyes to 'burning' in warrior mode)",1],
  [888,"","\"aaah\"",0],
  [889,"","motion (sings \"ahh-tahoo\")",1],
  [890,"","\"baby\"",0],
  [891,"","\"ka ay tay oooh\", \"purr grrr uh oh\"",0],
  [892,"","\"mmm, good food\"",0],
  [893,"","",0],
  [900,"I have no personality developed yet...","",0],
  [901,"I'm a princess!","",0],
  [902,"I'm a diva!","",0],
  [903,"I'm a warrior!","",0],
  [904,"I'm a joker!","",0],
  [905,"I'm a gossip queen!","",0],
  [906,"My personality is #906 [SNUGGLEBY]","906 [SNUGGLEBY]',",0],
  [907,"My personality is #907 [SASSBY]","907 [SASSBY]',",0],
  [908,"My personality is #908 [SCOFFBY]","908 [SCOFFBY]',",0],
  [909,"My personality is #909 [CHUCKLEBY]","909 [CHUCKLEBY]',",0],
  [910,"My personality is #910 [GASSBY]","910 [GASSBY]',",0],
  [911,"My personality is #911 [LATEBY]","911 [LATEBY]',",0]
];

const DICTIONARY = {
  "0": "Me like. / Kah toh-loo.",
  "1": "Me like you. / Kah toh-loo oo-nye.",
  "2": "Upside down! / Oo-tye nah-bah!",
  "3": "Listen. / Ay-ay-lee-koo.",
  "4": "Singing time. / Wee-tee toh-toh.",
  "5": "Big joke! / Dah loo-loo!",
  "6": "More talk. / Koh-koh noo-noo.",
  "7": "Yes. Thank you. / Ee-tay. Dah-kah-oo-nye.",
  "8": "Me like talk! / Kah toh-loo noo-noo!",
  "9": "Talk big fun! / Noo-noo dah doo-ay.",
  "10": "Yes no yes no. / Ee-tay boo ee-tay boo.",
  "11": "Good food! / Ee-day ah-tah!",
  "12": "More! More! More! / Koh-koh! Koh-koh! Koh-koh!",
  "13": "Good morning! / Dah-ay-loh-oo-tye!",
  "14": "Good game! / Ee-day doo-ay-loo-lah!",
  "15": "Me see you. / Kah ay-ay oo-nye.",
  "16": "Me love you. / Kah may-may oo-nye.",
  "17": "Love friend! / May-may noo-lah!",
  "18": "Big happy. / Dah noo-loo.",
  "19": "Pet more. / Ah-may koh-koh.",
  "20": "Big noise! / Dah bah-boo!",
  "21": "Please hug me. / Doo-moh may-lah kah.",
  "22": "Huh? Good morning. / Doo? Dah-ay-loh-oo-tye.",
  "23": "Little noise. / Dee bah-boo.",
  "24": "Tickle. / Nee-tye.",
  "25": "Noise! / Bah-boo!",
  "26": "Happy. / Noo-loo.",
  "27": "Hug Me / May-lah Kah.",
  "28": "Hey! No! / Hey! Boo!",
  "29": "Me very happy, yeah! / Kah mee-mee noo-loo, wah!",
  "30": "Me like. Again please. / Kah toh-loo. Koh-koh doo-moh.",
  "31": "Uh-oh! Me no like.Uh-oh! / Kah no toh-loo.",
  "32": "Me scared! / Kah dah-boh-bay!",
  "33": "Me! / Kahhh!",
  "34": "Me down! / Kah nah-bah!",
  "35": "Me Me Me! / Kah kah kahhhh!",
  "36": "No feel good! / Boo koo-doh e-day!",
  "37": "Yeah! Yes! / Wah! Ee-tay!",
  "38": "Dance! / Noh-lah!",
  "39": "Me like dance. / Kah toh-loo noh-lah.",
  "40": "Like, dance baby! / Tay, noh-lah bay-bee!",
  "42": "No joke. / Boo loo-loo.",
  "43": "JokeJokeJokeJoke! / LooLooLooLooLoo!",
  "44": "Genius! / Dah-way!",
  "45": "Pretty noise! / Ee-kah bah-boo!",
  "46": "Big no! / Dah-boo!",
  "47": "Me hungry! / Kah Ay-tay!",
  "48": "No hungry! / Boo ay-tay!",
  "49": "Me no happy. / Kah boo noo-loo.",
  "50": "Me very hungry! / Kah mee-mee ay-tay!",
  "51": "Please, hungry! / Doo-moh, ay-tay!",
  "52": "Please talk. / Doo-moh noo-noo.",
  "53": "Me tired. / Kah way-loh.",
  "54": "Where are you? / Oo-nye doo?",
  "55": "Funny talk. / Doo-loo noo-noo.",
  "56": "Yeah, yeah, yeah?! / Wah, wah, wah?!",
  "57": "Over, over, dizzy, me change! / Oo-bah, oo-bah, ay-way, kah boo-tay!",
  "58": "Like singing! / Toh-loo wee-tee!",
  "59": "Like, me LIKE! / Tay, kah TAY!",
  "60": "Like, me hear you! / Tay, mah ay-ay-lee-koo oo-nye!",
  "61": "Like, listen! / Tay, ay-ay-lee-koo!",
  "62": "Me dance! / Kah noh-lah!",
  "63": "Hmm? Okay! / Doo? Oh-kay!",
  "64": "Huh? What? No! / Huh? Doo? Boo!",
  "65": "No! Me dance! / Boo! Kah noh-lah!",
  "66": "What? What? Whaaaa!!!? / Doo? Doo? Doooooo!!!?",
  "67": "Wasssssupppp, buddy! / Dooooo Ooooooo-tye, noo-lah!!!!",
  "68": "Shake, baby! / Koo-bah, bay-bee!",
  "69": "Me beautiful! / Kah ee-kah!",
  "70": "Me beautiful diamond! / Kah ee-kah ay-koo!",
  "71": "Yeah yeah yeah talk! / Wah wah wah noo-noo!",
  "72": "â¦happy, yeah yeah, yeah yeah! / Shana noo-loo mah, shana wah wah moo-loo nah!",
  "73": "Dance time. / Noh-lah toh-toh.",
  "74": "Dance monster, like like, dance, buddy buddy, buddy, monster, like like, happy / Noh-lah moh-moh tay tay noo-lah noo-lah noo-lah moh-moh tay tay noo-loo.",
  "75": "OMG! Good sound! / Oh-kah-tee! Ee-day lee-koo!",
  "76": "Like, blah blah blah! / Tay, blah blah blah!",
  "77": "Beautiful, baby! / Ee-kah, bay-bee!",
  "78": "What's up? / Doo-oo-tye?",
  "79": "Finally. / Oo-tah-toh-toh.",
  "80": "Finally! Yeah! / Oo-tah-toh-toh! Yeah!",
  "81": "Funny dance. / Doo-loo noh-lah.",
  "82": "Good play! / Ee-day loo-lay!",
  "83": "Play, yeah. / Loo, wah.",
  "84": "Party time, baby! / Dah-noh-lah, bay-bee!",
  "86": "Good sound! / Ee-day lee-koo!",
  "87": "More good sound! / Koh-koh ee-day lee-koo!",
  "88": "Watch me! Watch me! / Ay-ay kah!",
  "89": "Yay! Whassup? / Yay! Doo-oo-tye?",
  "90": "Yay! Me love dance!Yay! / Kah may-may noh-lah!",
  "91": "What's up? You dance! / Doo-oo-tye? Oo-nye noh-lah!",
  "92": "Dance! Dance! Dance! Dance! / Noh-lah! Noh-lah! Noh-lah! Noh-lah!",
  "93": "Party time! Yea! / Daaah-nohhhh-lahhhhh! Wah!",
  "94": "Life is dance! / Tee noh-la!",
  "95": "Party time! / Dah-noh-lah!",
  "96": "Me like music! / Kah toh-loo ee-kah-lee-koo!",
  "97": "You dance! / Oo-nye noh-lah!",
  "98": "You happy? / Oo-nye noo-loo?",
  "99": "No! You party monster! / Boo! Oo-nye dah-no-lah moh-moh!",
  "100": "Funny! / Doo-loo!",
  "101": "Good joke! / Ee-day loo-loo!",
  "102": "You funny. / Oo-nye doo-loo.",
  "103": "No funny! / Boo doo-loo!",
  "104": "Me monster! / Kah moh moh! Kah moh moh!",
  "105": "Yay! You me talk.Yay! / Oo-nye kah noo-noo.",
  "106": "Monster noise / Moh-moh bah-boo",
  "107": "Dance monster! / Noh-lah moh-moh!",
  "108": "Talk monster! / Noo-noo moh-moh!",
  "109": "Yeeehaaa! You big monster! / Yeeehaaa! Oo-nye dah moh-moh!",
  "110": "You look funny. / Oo-nye ay-ay doo-loo.",
  "111": "Help! / Ah-noo!",
  "112": "Finally! Hungry! / Oo-tah-toh-toh! Ay-tay!",
  "113": "Like, Dance monster! Yeah! / Tay, noh-lah moh-moh! Wah!",
  "114": "Food. / Ah-tah.",
  "115": "No pet! / Boo ah-may!",
  "116": "No like! / Boo toh-loo!",
  "117": "No touch! / Boo ah!",
  "118": "Me talk monster! / Kah noo-noo moh-moh!",
  "119": "Me dance monster! / Kah Noh-lah moh-moh!",
  "120": "Very good. / Mee-mee ee-day.",
  "121": "Ok! Ok! Good! Yes! / Oh-kay! Oh-kay! Ee-Day! Ee-tay!",
  "122": "Life genius! / Tee dah-way!",
  "123": "Hey! Big no!Hey! / Dah boo!",
  "124": "Me dizzy! Feed! / Kah ay-way! Ah-tah!",
  "125": "Oh me genius, love dance, oh me geniusâ¦ / Oh kah dah-way dee dee doo doo may-may noo-lah oh kah dah-way",
  "126": "Feed me! / Ah-tah kah!",
  "127": "Listen, listen, look listen, ooh sound, oh babyâ¦ / Ay-ay-lee-koo, ay-ay-lee-koo, ay-ay ay-ay-lee-koo, ooh lee-koo, oh, bay-beeâ¦",
  "128": "Oooh, you no good, good me genius, genius, genius, genius baby! / Oooh, oo-nye boo ee-day, ee-day kah dah-way, dah-way, dah-way, dah-way bay-bee!",
  "129": "So funny! / Doh doo-loo!",
  "130": "Music, baby! / Ee-kah-lee-koo, bay-bee!",
  "131": "Ahhh Big Genius! / Ahhh Dahhh Dahh-wayyyy!",
  "132": "Ohhhh myyyy goshhhh! / Ohhhh-kahhhh-teeeee!",
  "133": "Kiss, baby! / May-tah, bay-bee!",
  "134": "Me no healthy! / Kah boo koo-doh!",
  "135": "Like, no way! / Tay, dah-boo!",
  "136": "Yeah! Dude! / Wah! Deeee-dohhhh!",
  "138": "Whoaaaa! / Whoaaaa!",
  "139": "Oy! Huh? / Oy! Doo?",
  "140": "Me big dance! / Kah dah noh-lah!",
  "141": "Little dance! / Dee noh-lah!",
  "142": "Watch me dance! / Ay-ay kah noh-lah!",
  "143": "Dance! Yeah! / Noooh-Laaah! Wah!",
  "144": "Me tired. More food! / Kah way-loh. Koh-koh ah-tah!",
  "145": " Look good me, good sound, good sound, good soundâ¦ / Ay-ay ee-day kah, ee-day lee-koo, ee-day lee-koo, ee-day lee-kooâ¦",
  "146": "No like game! / Boo toh-loo doo-ay-loo-lah!",
  "147": "You pull! / Oo-nye ah-loo!",
  "148": "Yes! Uh-huh! / Ee-tay! Uh-huh!",
  "149": "Like, OK! / Tay, oh-kay!",
  "150": "Like, really? REALLY??? / Tay, doo? DOO???",
  "151": "Ahhh Big Genius! / Ahhh Dahhh Dahh-wayyyy!",
  "152": "Yes! Yes! Yes! / Ee-tay! Ee-tay! Ee-tay!",
  "153": "Ha! Dude! / Ha! Dee-doh!",
  "154": "Thank you. / Dah-kah-oo-nye.",
  "157": "Life good upside down. / Tee ee-day oo-tye nah-bah.",
  "158": "Me happy. / Kah noo-loo.",
  "159": "Life good! / Tee ee-day!",
  "160": "Dude! Dude good friend. / Dee-doh! Dee-doh ee-day noo-lah.",
  "161": "Ha! Dude! / Ha! Dee-doh!",
  "162": "Love you, dude! / May-may oo-nye, dee-doh!",
  "163": "Genius talk! / Dah-way noo-noo!",
  "164": "Me like friend. / Kah toh-loo noo-lah.",
  "165": "Me tough! / Kah tay-boo-koo!",
  "166": "Me happy dude. / Kah noo-loo dee-doh.",
  "167": "No fun. / Boo doo-ay.",
  "168": "Very very very very fun! / Mee-mee mee-mee mee-mee mee-mee doo-ay!",
  "169": "Me big dude. / Kah dah dee-doh.",
  "170": "More joke. / Koh-koh loo-loo.",
  "171": "Tickle! / Nee-tye!",
  "172": "Huh? You eat me? / Doo? oo-nye ay-tay kah?",
  "173": "Okay, uncle... / Oh-kay, oo-kah...",
  "174": "Play Play Play Play Play! / LooLooLooLooLooooo!",
  "175": "Ticke me! Now! / Nee-tye kah! Nee-way!",
  "176": "Oh, very very! / Ohhh, mee-mee mee-mee!",
  "178": "Whassssssupppppp! / Dooooo-ooooooo-tye!",
  "179": "Me dizzy. / Kah ay-way.",
  "180": "No dance. / Boo noh-lah.",
  "181": "Dance? Really? / Noh-lah? Doo?",
  "182": "Sweet! Uh-huh! Party! / Nee-may! Uh-huh! Dah-no-lah!",
  "185": "More! More! / Koh-koh! Koh-koh!",
  "187": "Me like tickle! / Kah toh-loo nee-tye!",
  "189": "Help! Me scared... NOT! / Ah-noo! Me dah-boh-bay...KAH-LOO-LOO!",
  "190": "Dude. What's up? / Dee-doh. Doo-oo-tye?",
  "191": "Monster! Help! / Moh-moh! Ah-noo!",
  "192": "You think me funny? / Oo-nye way kah doo-loo?",
  "195": "Please. / Doo-moh.",
  "196": "Dizzy! / Ay-way!",
  "197": "Me dizzy. / Kah ay-way.",
  "198": "Dizzy! Dizzy! / Ay-way! Ay-way!",
  "199": "Me no hungry. / Kah boo ay-tay.",
  "202": "More play! / Koh-koh loo-lay!",
  "204": "Uh-oh. / Uh-oh.",
  "206": "Like, when talk? / Tay, doo noo-noo?",
  "208": "Yeah? / Doo?",
  "209": "Yes! Uh-huh! / Ee-tay! Uh-huh!",
  "210": "Yeah! Hug time! / Wah! May-lah toh-toh!",
  "212": "When talk? / Doo noo-noo?",
  "213": "Hmm? Like, why hug? / Doo? Tay, doo may-lah?",
  "214": "Oh yeah! / Ohhhh wah!",
  "215": "No talk, no love! / Boo noo-noo, boo may-may!",
  "217": "Like, me dizzy. / Tay, kah ay-way.",
  "218": "You no good! / Oo-nye boo ee-day!",
  "219": "You no listen. / Oo-nye boo ay-ay-lee-koo.",
  "220": "Where friend? / Doo noo-lah?",
  "221": "Love it! / Dah-may-may!",
  "223": "Oh! / Oh!",
  "224": "Oh! Me like! Yeah! Yeah! Yeah!Oh! / Kah toh-loo! Wah! Wah! Wah!",
  "225": "Yeah! Yeah! Yeaaaahhh! / Wah! Wah! Waaaaaaahhhh!",
  "228": "Boringâ¦ / Boo-doo-ayâ¦",
  "238": "Dizzy sounds! / Ay-way lee-koo!",
  "239": "Noisy song. / Bah-boo wah-tee.",
  "242": "Like, you like song? / Tay, oo-nye toh-loo wah-tee?",
  "243": "No more noise! / Boo koh-koh bah-boo!",
  "244": "Huh? Oh! You play! / Doo? Oh! Oo-nye loo-lay!",
  "245": "Why joke? / Doo loo-loo?",
  "246": "Play game? / Loo doo-ay-loo-lah?",
  "247": "Hey! You funny? / Hey! Oo-nye doo-loo?",
  "248": "Hey! No more joke. / Hey! Boo koh-koh loo-loo.",
  "249": "Love tickle! / May-may nee-tye!",
  "250": "Sweet shake, baby! / Nee-may koo-bah, bay-bee!",
  "251": "You move me, uh-huh! / Oo-nye noh-bah kah, uh-huh!",
  "255": "Me see! / Kah ay-ay!",
  "256": "No way! / Daahhhh-boooo!",
  "258": "No way! Like, get out! / Dah-boo! Tay, bye-bye!",
  "261": "Like, me like! Like, to say like! Like! / Tay, kah toh-loo! Tay, noo-noo tay! Tay!",
  "262": "Like, you little talk! Me big talk! / Tay, oo-nye dee noo-noo! Kah dah noo-noo!",
  "263": "Talk talk talk talk! / Noo-noo noo-noo noo-noo noo-noo!",
  "264": "Talk more! / Noo-noo koh-koh!",
  "265": "Talk more! Talk more! / Noo-noo koh-koh! Noo-noo koh-koh!",
  "266": "You talk pretty, like love song! / Oo-nye noo-noo ee-kah, tay may-may wah-tee!",
  "267": "Like, friends love talking. / Tay, noo-lah may-may noo-noo.",
  "268": "Like, good hug. / Tay, ee-day may-lah.",
  "269": "Like, holding and talking! / Tay, ah koh noo-noo!",
  "270": "OMG! / Oh-kah-tee!",
  "271": "Like, yes! / Tay, ee-tay!",
  "273": "Talking is life. / Noo-noo tee.",
  "274": "You genius! / Oo-nye dah-way!",
  "275": "Like, whooaaa! / Tay, whooaaa!",
  "277": "No be worried, baby! / Boo boh boh-bay, bay-bee!",
  "278": "Huh? Me dreaming? / Doo? Kah way-loo?",
  "279": "Dude! You dreaming! / Dee-doh! Oo-nye way-loo!",
  "280": "Rock shake! / Boo-koo koo-bah!",
  "281": "Uh-huh! Uh-huh! Rock! / Uh-huh! Uh-huh! Boo-koo!",
  "282": "You rock! / Oo-nye boo-koo un-go-boh!",
  "283": "Me rock! Whooo! / Kah boo-koo! Whooo!",
  "284": "Me rock monster! / Kah boo-koo moh-moh!",
  "285": "Oy oy oy, monster! / Oy oy oy, moh-moh!",
  "286": "Ayyy! Joke monster! / Ayyy! Loo-loo moh-moh!",
  "287": "Genius dance! Whooo! / Dah-way noh-lah! Whooo!",
  "288": "Hug! Hug! / May-lah! May-lah!",
  "289": "Funny sound! / Doo-loo lee-koo!",
  "290": "Funny noise! / Doo-loo bah-boo!",
  "291": "Oh yes! / Oh ee-tay!",
  "292": "Say what? / Noo-noo doo?",
  "293": "Say no more. / Noo-noo boo koh-koh.",
  "294": "Hungry! Hungry! Help... / Ay-tay! Ay-tay! Ah-noo.",
  "295": "Song? / Wah-tee?",
  "296": "Yeah, baby! / Wah, bay-bee!",
  "297": "Seriously? / Loo-loo-doo?",
  "298": "Yeah baby! Yeah baby! / Wah bay-bee! Wah bay-bee!",
  "299": "Say more / Noo-noo koh-koh",
  "300": "Yay! / Yay!",
  "302": "What? Say more. / Doo? Noo-noo koh-koh.",
  "303": "Me hear you! / Kah ay-ay-lee-koo oo-nye!",
  "304": "Baby! Yes! / Bay-bee! Ee-tay!",
  "305": "Baby! / Bay-bee!",
  "306": "Again please. / Koh-koh doo-moh.",
  "307": "Happy! / Noo-loo!",
  "308": "Hey, me very happy, yeah! / Hey, kah mee-mee noo-loo, wah!",
  "309": "Love you! Whoooo! / May-may oo-nye! Whoooo!",
  "310": "No happy. / Boo noo-loo.",
  "311": "Me see you. / Kay ay-ay oo-nye.",
  "312": "No feel good. / Boo koo-doh e-day.",
  "313": "Please, hungry! Please, hungry! / Doo-moh, ay-tay!",
  "314": "Me sleep. / Kah way-loh.",
  "315": "What? Tell me more. / Doo? Wee-tah kah koh-koh.",
  "316": "Pet more!Mmmmm! / Ah-may koh-koh!",
  "317": "Not bad. / Boo boo-dah.",
  "318": "Uh-uh. Pet bad. / Uh-uh. Ah-may boo-dah.",
  "319": "Yay! Me like! / Yay! Kah toh-loo!",
  "320": "Uh-uh. / Uh-uh.",
  "321": "Okay, you love me. / Oh-kay, oo-nye may-may kah.",
  "322": "Me love you! / Kah may-may oo-nye!",
  "323": "Uh-huh! Uh-huh! Uh-huh! / Uh-huh! Uh-huh! Uh-huh!",
  "324": "Party! / Dah-noh-lah!",
  "325": "Oh baby! / Oh bay-bee!",
  "326": "Good joke. / Ee-day loo-loo.",
  "327": "No time! / Boo toh-toh!",
  "328": "You me talk. / Oo-nye kah noo-noo.",
  "329": "Uh-huh! / Uh-huh!",
  "330": "Okay. / Oh-kay.",
  "331": "Uh-uh. / Uh-huh.",
  "332": "No! No! / Dah-boo! Dah-boo!",
  "333": "Tell me moreâ¦ / Noo-noo koh-koh!",
  "334": "Me hungry. / Kah ay-tay.",
  "335": "Me big dance. / Kah dah noh-lah.",
  "336": "Me like noise! / Kah toh-loo bah-boo.",
  "337": "Me like! / Kah toh-loo!",
  "338": "You big talk. / Oo-nye dah noo-noo.",
  "339": "Over, over, dizzy, me change! / Oo-bah, o-bah, ay-way, kah boo-tay!",
  "340": "Hey! No touch! / Hey! Boo ah!",
  "341": "More! More! More! More! / Koh-koh! Koh-koh! Koh-koh! Koh-koh!",
  "342": "Again! More! / Koh-koh! Koh!",
  "343": "You like me funny? / Oo-nye toh-loo kah doo-loo?",
  "344": "Dude. Not funny. / Dee-doh. Boo doo-loo.",
  "345": "Me dizzy! / Kah ay-way!",
  "346": "Thank you, thank...you... / Dah-kah-oo-nye, dah-kah...oo-nye...",
  "347": "No me hungry. / No kah ay-tay.",
  "348": "Yea! Yea! / Wah! Wah!",
  "349": "You me dance. / Oo-nye kah noh-lah.",
  "650": "Uh-huh! / Uh-huh!",
  "651": "That's right! / Boh-ee-tay!",
  "652": "Yeah yeah yeah! Very good! / Wah wah wah! Mee-mee ee-day!",
  "653": "Hmm? Pet time? / Doo? Ah-may toh-toh?",
  "654": "Huh? Okay! / Doo? Oh-kay!",
  "655": "Sound time? / Lee-koo toh-toh?",
  "656": "Like, you funny! / Tay, oo-nye doo-loo!",
  "657": "Yeah! Like, mmm-kay! / Wah! Tay, mmm-kay!",
  "658": "What? Really? Ohhhh! / Doo? Loo-loo-doo? Ohhhh!",
  "659": "Ohhh yeah! You go, buddy! / Ohhh wah! Oo-nye bye-bye, noo-lah!",
  "660": "Oh, that's right! You genius, friend! / Oh, boh-ee-tay! Oo-nye dah-way, noo-lah!",
  "661": "OMG! What? / Oh kah-teee! Doo?",
  "662": "OMG! What? Really? / Oh kah-tee! Doo? Loo-loo-doo?",
  "663": "Like, finally! / Tay, oo-tah-toh-toh!",
  "664": "Yeah! Yeah! Yeah! Like, yippee! / Wah! Wah! Wah! Tay, yippee!",
  "665": "Uh-huh! Talk, more talk, yeah! / Uh-huh! Noo-noo, koh-koh noo-noo, wah!",
  "666": "OMG! Like, oh, my, gosh! / Oh kah-tee! Tay, oh, kah, tee.",
  "667": "Like, me sad. / Tay, kah boo-noo-loo.",
  "668": "Like, you look funny. / Tay, oo-nye ay-ay doo-loo.",
  "669": "Like, path high. / Tay, bye-way oo.",
  "670": "Like, me hungry! / Tay, kah ay-tay!",
  "671": "No! No! No! Really? / Boo! Boo! Boo! Dooo?",
  "672": "Like, over, over! Over, over! Over,over! More talk, more talk, more talk, more talk! OMG! / Tay, oo-bah, oo-bah! Ooh-bah, oo-bah! Koh noo-noo, koh noo-noo, koh noo-noo, koh noo-noo, OH KAH TEE!",
  "673": "Yay! Talk Time! / Yay! Noo-noo toh-toh!",
  "674": "Hey! / Hey!",
  "675": "Yeah! / Wah!",
  "676": "Really? Oh! / Loo-loo-doo? Oh!",
  "677": "OK! / Oh-kay!",
  "678": "Oh yeah! Uh-huh! / Oh wah! Uh-huh!",
  "679": "Oh yeah! Oh yeah! / Oh wah! Oh wah!",
  "680": "Bye-bye, bye-bye! / Bye-bye, bye-bye!",
  "681": "Yeah! Yeah! / Wah! Wah!",
  "682": "OK! / Oh-kay!",
  "683": "Yeah! Yeah! Yeah! / Wah! Wah! Wah!",
  "684": "What's up? / Doo-oo-tye?",
  "685": "Huh? Hey! / Doo? Hey!",
  "686": "Huh? Really? / Doo? Loo-loo-doo?",
  "687": "Whoohoo! Uh-huh! Oh yeah / Uh-huh! Oh wah!",
  "688": "Hey, hey, hey! / Hey, hey, hey!",
  "689": "Uh-huh! Yeah! Like, mmm-kay! / Uh-huh! Wah! Tay, mmm-kay!",
  "690": "No way?! / Dah-boo!?!",
  "691": "OK! Yeah! / Oh-kay! Wah!",
  "694": "Oh. me see! / Oh. Kah ay-ay!",
  "697": "Really? / Doooo?"
};

D.CHECKSUMS_64 = CHECKSUMS_64;
D.CMD_LIST = CMD_LIST;
D.DICTIONARY = DICTIONARY;
})(typeof window !== 'undefined' ? window : globalThis);
